// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

public struct TorkPiiCountry: Sendable {
    public let code: String
    public let name: String
    public let callingCode: String
    public let bloc: Bool
    public let patterns: [String]
}

public struct TorkPiiPattern: Sendable {
    public let name: String
    public let country: String
    public let kind: String
    public let regex: String
    public let redaction: String
    public let type: String
    public let label: String
    public let requiresKeyword: Bool
    public let alwaysOn: Bool
    public let keywords: [String]
    public let wholeWordKeywords: [String]
    public let nearMissKeywords: [String]
    public let nearMissFallback: Bool
    public let checksum: String?
    public let checksumRequired: Bool
}

public struct TorkPiiSignal: Sendable {
    public let country: String
    public let regex: String
    public let flags: String
    public let keywords: [String]
    public let wholeWordKeywords: [String]
    public let activates: String
}

public let torkPiiRegistryVersion = "1.2.0"
public let torkPiiContentHash = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26"

// The keyword gate is ASYMMETRIC — see README.md, rule 3.
public let torkPiiKeywordWindowBefore = 60
public let torkPiiKeywordWindowAfter = 40
public let torkPiiContextWindow = 60
public let torkPiiLabelWindow = 60
public let torkPiiLabelReach = 25

public let torkPiiNearMissRedaction = "[NATIONAL_ID_REDACTED]"
public let torkPiiNearMissType = "national_id_near_miss"
public let torkPiiNearMissKinds: [String] = ["health_id", "national_id", "tax_id"]

public let torkPiiTableDelimiters: [String] = ["\t", "|", ";", ","]
public let torkPiiTableMaxHeaderLength = 32
public let torkPiiTableMaxHeaderWords = 4
public let torkPiiTableMinRows = 3
public let torkPiiTableMinCommaColumns = 3

public let torkPiiLabels: [String] = [
    #"AADHAAR"#,
    #"ABN"#,
    #"ACN"#,
    #"BVN"#,
    #"CA_PASSPORT"#,
    #"CA_PHONE"#,
    #"CA_POSTAL"#,
    #"CNIC"#,
    #"CNPJ"#,
    #"CODICE_FISCALE"#,
    #"CPF"#,
    #"EMIRATES_ID"#,
    #"GHANA_CARD"#,
    #"IFSC"#,
    #"ITIN"#,
    #"KRA_PIN"#,
    #"MEDICARE"#,
    #"MYKAD"#,
    #"MY_NUMBER"#,
    #"NATIONAL_ID"#,
    #"NHS"#,
    #"NIK"#,
    #"NIN"#,
    #"NINO"#,
    #"NRIC"#,
    #"PAN"#,
    #"PASSPORT"#,
    #"PHONE"#,
    #"PINCODE"#,
    #"PO_BOX"#,
    #"RESIDENT_ID"#,
    #"RFC"#,
    #"RRN"#,
    #"SIN"#,
    #"SORT_CODE"#,
    #"TAN"#,
    #"TAX_ID"#,
    #"TFN"#,
    #"UK_POSTCODE"#,
    #"ZA_ID"#,
]

public let torkPiiReferenceLabels: [String] = [
    #"order"#,
    #"invoice"#,
    #"purchase order"#,
    #"po no"#,
    #"po number"#,
    #"job number"#,
    #"job no"#,
    #"booking"#,
    #"tracking"#,
    #"consignment"#,
    #"waybill"#,
    #"airway bill"#,
    #"awb"#,
    #"docket"#,
    #"quote"#,
    #"quotation"#,
    #"ticket"#,
    #"receipt"#,
    #"serial number"#,
    #"asset tag"#,
    #"part number"#,
    #"stock code"#,
    #"batch"#,
    #"shipment"#,
    #"dispatch note"#,
    #"delivery note"#,
    #"work order"#,
    #"contract number"#,
    #"policy number"#,
    #"meter number"#,
    #"case id"#,
    #"bestelling"#,
    #"bestelnommer"#,
    #"faktuur"#,
    #"kwotasie"#,
    #"commande"#,
    #"facture"#,
    #"devis"#,
    #"bon de livraison"#,
    #"expédition"#,
    #"expedition"#,
    #"pedido"#,
    #"fatura"#,
    #"factura"#,
    #"orçamento"#,
    #"orcamento"#,
    #"presupuesto"#,
    #"remito"#,
    #"pesanan"#,
    #"nombor pesanan"#,
    #"invois"#,
    #"sebut harga"#,
    #"penghantaran"#,
    #"resit"#,
    #"आदेश"#,
    #"क्रय आदेश"#,
    #"चालान"#,
    #"कोटेशन"#,
    #"रसीद"#,
    #"آرڈر"#,
    #"انوائس"#,
    #"رسید"#,
    #"کوٹیشن"#,
    #"ترسیل"#,
    #"طلب"#,
    #"أمر شراء"#,
    #"فاتورة"#,
    #"عرض سعر"#,
    #"إيصال"#,
    #"شحنة"#,
    #"بوليصة"#,
    #"注文"#,
    #"注文番号"#,
    #"発注"#,
    #"発注番号"#,
    #"請求書"#,
    #"請求番号"#,
    #"伝票"#,
    #"伝票番号"#,
    #"見積"#,
    #"見積番号"#,
    #"管理番号"#,
    #"在庫番号"#,
    #"受注"#,
    #"出荷"#,
    #"订单"#,
    #"訂單"#,
    #"订单编号"#,
    #"訂單編號"#,
    #"发票"#,
    #"發票"#,
    #"采购"#,
    #"採購"#,
    #"报价"#,
    #"報價"#,
    #"运单"#,
    #"運單"#,
    #"物料编号"#,
    #"物料編號"#,
    #"库存"#,
    #"庫存"#,
    #"주문"#,
    #"주문번호"#,
    #"구매주문"#,
    #"송장"#,
    #"견적"#,
    #"견적서"#,
    #"운송장"#,
    #"자재번호"#,
    #"재고번호"#,
    #"ใบสั่งซื้อ"#,
    #"เลขที่ใบสั่งซื้อ"#,
    #"ใบแจ้งหนี้"#,
    #"ใบเสนอราคา"#,
    #"ใบส่งของ"#,
    #"รหัสพัสดุ"#,
    #"ใบงาน"#,
]

public let torkPiiGenericIdKeywords: [String] = [
    #"national id"#,
    #"national identity"#,
    #"national identification"#,
    #"national number"#,
    #"national code"#,
    #"identity number"#,
    #"identification number"#,
    #"id number"#,
    #"citizen id"#,
    #"citizen number"#,
    #"resident id"#,
    #"resident number"#,
    #"civil id"#,
    #"civil number"#,
    #"civil registration"#,
    #"personal number"#,
    #"personal identity"#,
    #"personal code"#,
    #"personal id"#,
    #"tax identification"#,
    #"tax reference"#,
    #"taxpayer number"#,
    #"taxpayer id"#,
]

public let torkPiiLocalIdKeywords: [String] = [
    #"cedula"#,
    #"cédula"#,
    #"iqama"#,
    #"nadra"#,
    #"cnic"#,
    #"aadhaar"#,
    #"voen"#,
    #"vöen"#,
    #"егн"#,
    #"oib"#,
    #"cpr-nummer"#,
    #"cpr nummer"#,
    #"kennitala"#,
    #"personnummer"#,
    #"adoazonosito"#,
    #"adóazonosító"#,
    #"szemelyi azonosito"#,
    #"személyi azonosító"#,
    #"kimlik"#,
    #"рнокпп"#,
    #"nid number"#,
    #"sars income tax"#,
]

public let torkPiiCountries: [TorkPiiCountry] = [
    TorkPiiCountry(code: #"AU"#, name: #"Australia"#, callingCode: #"61"#, bloc: false, patterns: [#"au_tfn"#, #"au_abn"#, #"au_medicare"#, #"au_acn"#, #"au_phone_intl"#]),
    TorkPiiCountry(code: #"US"#, name: #"United States"#, callingCode: #"1"#, bloc: false, patterns: [#"us_itin"#, #"us_passport_alpha"#]),
    TorkPiiCountry(code: #"GB"#, name: #"United Kingdom"#, callingCode: #"44"#, bloc: false, patterns: [#"uk_phone_full"#, #"uk_sort_code"#, #"uk_nino"#, #"uk_nhs"#, #"uk_postcode"#]),
    TorkPiiCountry(code: #"EU"#, name: #"European Union"#, callingCode: #""#, bloc: true, patterns: [#"de_tax_id"#]),
    TorkPiiCountry(code: #"AE"#, name: #"United Arab Emirates"#, callingCode: #"971"#, bloc: false, patterns: [#"emirates_id"#, #"uae_phone"#, #"uae_landline"#, #"po_box"#]),
    TorkPiiCountry(code: #"SA"#, name: #"Saudi Arabia"#, callingCode: #"966"#, bloc: false, patterns: [#"sa_national_id"#, #"sa_phone"#]),
    TorkPiiCountry(code: #"NG"#, name: #"Nigeria"#, callingCode: #"234"#, bloc: false, patterns: [#"ng_nin"#, #"ng_bvn"#, #"ng_phone"#]),
    TorkPiiCountry(code: #"IN"#, name: #"India"#, callingCode: #"91"#, bloc: false, patterns: [#"in_aadhaar"#, #"in_pan"#, #"in_phone"#, #"in_ifsc"#, #"in_pincode"#]),
    TorkPiiCountry(code: #"JP"#, name: #"Japan"#, callingCode: #"81"#, bloc: false, patterns: [#"jp_my_number"#, #"jp_phone_intl"#, #"jp_phone_national"#]),
    TorkPiiCountry(code: #"CN"#, name: #"China"#, callingCode: #"86"#, bloc: false, patterns: [#"cn_resident_id"#, #"cn_phone_intl"#, #"cn_phone_national"#]),
    TorkPiiCountry(code: #"KR"#, name: #"South Korea"#, callingCode: #"82"#, bloc: false, patterns: [#"kr_rrn"#, #"kr_phone_intl"#, #"kr_phone_national"#]),
    TorkPiiCountry(code: #"BR"#, name: #"Brazil"#, callingCode: #"55"#, bloc: false, patterns: [#"br_cpf"#, #"br_cnpj"#]),
    TorkPiiCountry(code: #"CA"#, name: #"Canada"#, callingCode: #"1"#, bloc: false, patterns: [#"ca_sin"#, #"ca_phone"#, #"ca_postal_code"#, #"ca_passport"#]),
    TorkPiiCountry(code: #"ZA"#, name: #"South Africa"#, callingCode: #"27"#, bloc: false, patterns: [#"za_id_number"#, #"za_phone"#]),
    TorkPiiCountry(code: #"GH"#, name: #"Ghana"#, callingCode: #"233"#, bloc: false, patterns: [#"gh_ghana_card"#]),
    TorkPiiCountry(code: #"IT"#, name: #"Italy"#, callingCode: #"39"#, bloc: false, patterns: [#"it_codice_fiscale"#]),
    TorkPiiCountry(code: #"KE"#, name: #"Kenya"#, callingCode: #"254"#, bloc: false, patterns: [#"ke_kra_pin"#]),
    TorkPiiCountry(code: #"MU"#, name: #"Mauritius"#, callingCode: #"230"#, bloc: false, patterns: [#"mu_tan"#]),
    TorkPiiCountry(code: #"MX"#, name: #"Mexico"#, callingCode: #"52"#, bloc: false, patterns: [#"mx_rfc"#]),
    TorkPiiCountry(code: #"MY"#, name: #"Malaysia"#, callingCode: #"60"#, bloc: false, patterns: [#"my_mykad"#]),
    TorkPiiCountry(code: #"PK"#, name: #"Pakistan"#, callingCode: #"92"#, bloc: false, patterns: [#"pk_cnic"#]),
    TorkPiiCountry(code: #"SG"#, name: #"Singapore"#, callingCode: #"65"#, bloc: false, patterns: [#"sg_nric"#]),
    TorkPiiCountry(code: #"TH"#, name: #"Thailand"#, callingCode: #"66"#, bloc: false, patterns: [#"th_national_id"#]),
    TorkPiiCountry(code: #"ID"#, name: #"Indonesia"#, callingCode: #"62"#, bloc: false, patterns: [#"id_nik"#]),
]

// NSRegularExpression (ICU) is the tightest engine of the eleven; every
// pattern is written in the subset it shares with RE2.
public let torkPiiPatterns: [TorkPiiPattern] = [
    TorkPiiPattern(
        name: #"au_tfn"#,
        country: #"AU"#,
        kind: #"tax_id"#,
        regex: #"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: #"[TFN_REDACTED]"#,
        type: #"au_tfn"#,
        label: #"TFN"#,
        requiresKeyword: true,
        alwaysOn: true,
        keywords: [#"tfn"#, #"tax file"#, #"tax number"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"au_tfn"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"au_abn"#,
        country: #"AU"#,
        kind: #"company"#,
        regex: #"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: #"[ABN_REDACTED]"#,
        type: #"au_abn"#,
        label: #"ABN"#,
        requiresKeyword: true,
        alwaysOn: true,
        keywords: [#"abn"#, #"business number"#, #"australian business"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"au_abn"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"au_medicare"#,
        country: #"AU"#,
        kind: #"health_id"#,
        regex: #"\b\d{4}[ \t]?\d{5}[ \t]?\d{1}\b"#,
        redaction: #"[MEDICARE_REDACTED]"#,
        type: #"au_medicare"#,
        label: #"MEDICARE"#,
        requiresKeyword: true,
        alwaysOn: true,
        keywords: [#"medicare"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"au_medicare"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"au_acn"#,
        country: #"AU"#,
        kind: #"company"#,
        regex: #"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: #"[ACN_REDACTED]"#,
        type: #"au_acn"#,
        label: #"ACN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"acn"#, #"company number"#, #"australian company"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"au_phone_intl"#,
        country: #"AU"#,
        kind: #"phone"#,
        regex: #"\+61[ \t]?[2-478](?:[ \t]?\d){8}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"au_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"us_itin"#,
        country: #"US"#,
        kind: #"tax_id"#,
        regex: #"\b9\d{2}-[7-9]\d-\d{4}\b"#,
        redaction: #"[ITIN_REDACTED]"#,
        type: #"us_itin"#,
        label: #"ITIN"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"us_passport_alpha"#,
        country: #"US"#,
        kind: #"passport"#,
        regex: #"\b[A-Z]\d{8}\b"#,
        redaction: #"[PASSPORT_REDACTED]"#,
        type: #"us_passport"#,
        label: #"PASSPORT"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"passport"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uk_phone_full"#,
        country: #"GB"#,
        kind: #"phone"#,
        regex: #"(?:\+44[ \t]?|\b0)(?:7\d{3}|\d{2,4})[ \t]?\d{3,4}[ \t]?\d{3,4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"uk_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uk_sort_code"#,
        country: #"GB"#,
        kind: #"bank"#,
        regex: #"\b\d{2}-\d{2}-\d{2}\b"#,
        redaction: #"[SORT_CODE_REDACTED]"#,
        type: #"uk_sort_code"#,
        label: #"SORT_CODE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"sort code"#, #"sort-code"#, #"bank"#, #"account"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uk_nino"#,
        country: #"GB"#,
        kind: #"national_id"#,
        regex: #"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b"#,
        redaction: #"[NINO_REDACTED]"#,
        type: #"national_id"#,
        label: #"NINO"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"national insurance"#, #"ni number"#, #"nino"#, #"ni:"#, #"insurance number"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uk_nhs"#,
        country: #"GB"#,
        kind: #"health_id"#,
        regex: #"\b\d{3}[ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[NHS_REDACTED]"#,
        type: #"health_id"#,
        label: #"NHS"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"nhs"#, #"national health"#, #"nhs number"#, #"health service"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"uk_nhs"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"uk_postcode"#,
        country: #"GB"#,
        kind: #"postcode"#,
        regex: #"\b[A-Z]{1,2}\d[A-Z\d]?[ \t]?\d[A-Z]{2}\b"#,
        redaction: #"[UK_POSTCODE_REDACTED]"#,
        type: #"postal_code"#,
        label: #"UK_POSTCODE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"postcode"#, #"post code"#, #"uk"#, #"united kingdom"#, #"britain"#, #"england"#, #"scotland"#, #"wales"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"de_tax_id"#,
        country: #"EU"#,
        kind: #"tax_id"#,
        regex: #"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: #"[TAX_ID_REDACTED]"#,
        type: #"de_tax_id"#,
        label: #"TAX_ID"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"steuer"#, #"tax id"#, #"steuernummer"#, #"idnr"#, #"steueridentifikation"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"de_steuer_id"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"emirates_id"#,
        country: #"AE"#,
        kind: #"national_id"#,
        regex: #"\b784-?\d{4}-?\d{7}-?\d\b"#,
        redaction: #"[EMIRATES_ID_REDACTED]"#,
        type: #"emirates_id"#,
        label: #"EMIRATES_ID"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"ae_emirates_id"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uae_phone"#,
        country: #"AE"#,
        kind: #"phone"#,
        regex: #"(?:\+971[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"uae_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"uae_landline"#,
        country: #"AE"#,
        kind: #"phone"#,
        regex: #"(?:\+971[ \t]?|\b0)[2-4679][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"uae_landline"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"po_box"#,
        country: #"AE"#,
        kind: #"postcode"#,
        regex: #"\b[Pp]\.?[Oo]\.?[ \t]*[Bb]ox[ \t]+\d{3,6}\b"#,
        redaction: #"[PO_BOX_REDACTED]"#,
        type: #"po_box"#,
        label: #"PO_BOX"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"sa_national_id"#,
        country: #"SA"#,
        kind: #"national_id"#,
        regex: #"\b[12]\d{9}\b"#,
        redaction: #"[NATIONAL_ID_REDACTED]"#,
        type: #"sa_national_id"#,
        label: #"NATIONAL_ID"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"national id"#, #"iqama"#, #"national identification"#, #"resident id"#, #"saudi id"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"sa_national_id"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"sa_phone"#,
        country: #"SA"#,
        kind: #"phone"#,
        regex: #"(?:\+966[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"sa_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ng_nin"#,
        country: #"NG"#,
        kind: #"national_id"#,
        regex: #"\b\d{11}\b"#,
        redaction: #"[NIN_REDACTED]"#,
        type: #"ng_nin"#,
        label: #"NIN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"nin"#, #"national id"#, #"national identification"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ng_bvn"#,
        country: #"NG"#,
        kind: #"bank"#,
        regex: #"\b\d{11}\b"#,
        redaction: #"[BVN_REDACTED]"#,
        type: #"ng_bvn"#,
        label: #"BVN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"bvn"#, #"bank verification"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ng_phone"#,
        country: #"NG"#,
        kind: #"phone"#,
        regex: #"(?:\+234[ \t]?|\b0)[789]0[1-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"ng_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"in_aadhaar"#,
        country: #"IN"#,
        kind: #"national_id"#,
        regex: #"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        redaction: #"[AADHAAR_REDACTED]"#,
        type: #"in_aadhaar"#,
        label: #"AADHAAR"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"aadhaar"#, #"aadhar"#, #"uid"#, #"unique identification"#, #"aadhaar number"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"verhoeff"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"in_pan"#,
        country: #"IN"#,
        kind: #"tax_id"#,
        regex: #"\b[A-Z]{5}\d{4}[A-Z]\b"#,
        redaction: #"[PAN_REDACTED]"#,
        type: #"in_pan"#,
        label: #"PAN"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"in_phone"#,
        country: #"IN"#,
        kind: #"phone"#,
        regex: #"(?:\+91[ \t]?|\b0|\b)[6-9]\d{4}[ \t]?\d{5}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"in_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"in_ifsc"#,
        country: #"IN"#,
        kind: #"bank"#,
        regex: #"\b[A-Z]{4}0[A-Z0-9]{6}\b"#,
        redaction: #"[IFSC_REDACTED]"#,
        type: #"in_ifsc"#,
        label: #"IFSC"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"in_pincode"#,
        country: #"IN"#,
        kind: #"postcode"#,
        regex: #"\b[1-9]\d{5}\b"#,
        redaction: #"[PINCODE_REDACTED]"#,
        type: #"in_pincode"#,
        label: #"PINCODE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"pin code"#, #"pincode"#, #"postal code"#, #"zip"#, #"address"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"jp_my_number"#,
        country: #"JP"#,
        kind: #"national_id"#,
        regex: #"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        redaction: #"[MY_NUMBER_REDACTED]"#,
        type: #"jp_my_number"#,
        label: #"MY_NUMBER"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"my number"#, #"individual number"#, #"マイナンバー"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"jp_my_number"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"jp_phone_intl"#,
        country: #"JP"#,
        kind: #"phone"#,
        regex: #"\+81[ \t-]?[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"jp_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"jp_phone_national"#,
        country: #"JP"#,
        kind: #"phone"#,
        regex: #"\b0[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"jp_phone"#,
        label: #"PHONE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"phone"#, #"telephone"#, #"tel"#, #"mobile"#, #"cell"#, #"fax"#, #"call"#, #"contact"#, #"whatsapp"#, #"hotline"#, #"landline"#, #"電話"#, #"電話番号"#, #"携帯"#, #"携帯番号"#, #"でんわ"#, #"电话"#, #"手机"#, #"手機"#, #"전화"#, #"휴대"#, #"휴대폰"#, #"연락처"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"cn_resident_id"#,
        country: #"CN"#,
        kind: #"national_id"#,
        regex: #"\b\d{6}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[0-9Xx]\b"#,
        redaction: #"[RESIDENT_ID_REDACTED]"#,
        type: #"cn_resident_id"#,
        label: #"RESIDENT_ID"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"resident id"#, #"resident identity"#, #"identity card"#, #"id card"#, #"national id"#, #"id number"#, #"id no"#, #"id:"#, #"id ="#, #"identity number"#, #"hukou"#, #"身份证"#, #"身份證"#, #"居民身份证"#, #"居民身份證"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"cn_resident_id"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"cn_phone_intl"#,
        country: #"CN"#,
        kind: #"phone"#,
        regex: #"\+86[ \t-]?1[3-9]\d{9}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"cn_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"cn_phone_national"#,
        country: #"CN"#,
        kind: #"phone"#,
        regex: #"\b1[3-9]\d{9}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"cn_phone"#,
        label: #"PHONE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"phone"#, #"telephone"#, #"tel"#, #"mobile"#, #"cell"#, #"fax"#, #"call"#, #"contact"#, #"whatsapp"#, #"hotline"#, #"landline"#, #"電話"#, #"電話番号"#, #"携帯"#, #"携帯番号"#, #"でんわ"#, #"电话"#, #"手机"#, #"手機"#, #"전화"#, #"휴대"#, #"휴대폰"#, #"연락처"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"kr_rrn"#,
        country: #"KR"#,
        kind: #"national_id"#,
        regex: #"\b\d{6}-?[1-4]\d{6}\b"#,
        redaction: #"[RRN_REDACTED]"#,
        type: #"kr_rrn"#,
        label: #"RRN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"resident registration"#, #"resident number"#, #"registration number"#, #"rrn"#, #"jumin"#, #"juminbeonho"#, #"national id"#, #"id number"#, #"id no"#, #"id:"#, #"id ="#, #"identity number"#, #"주민등록번호"#, #"주민번호"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"kr_rrn"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"kr_phone_intl"#,
        country: #"KR"#,
        kind: #"phone"#,
        regex: #"\+82[ \t-]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"kr_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"kr_phone_national"#,
        country: #"KR"#,
        kind: #"phone"#,
        regex: #"\b01[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"kr_phone"#,
        label: #"PHONE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"phone"#, #"telephone"#, #"tel"#, #"mobile"#, #"cell"#, #"fax"#, #"call"#, #"contact"#, #"whatsapp"#, #"hotline"#, #"landline"#, #"電話"#, #"電話番号"#, #"携帯"#, #"携帯番号"#, #"でんわ"#, #"电话"#, #"手机"#, #"手機"#, #"전화"#, #"휴대"#, #"휴대폰"#, #"연락처"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"br_cpf"#,
        country: #"BR"#,
        kind: #"national_id"#,
        regex: #"\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b"#,
        redaction: #"[CPF_REDACTED]"#,
        type: #"br_cpf"#,
        label: #"CPF"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [#"cpf"#, #"cadastro de pessoas"#, #"receita federal"#],
        nearMissFallback: true,
        checksum: #"br_cpf"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"br_cnpj"#,
        country: #"BR"#,
        kind: #"company"#,
        regex: #"\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b"#,
        redaction: #"[CNPJ_REDACTED]"#,
        type: #"br_cnpj"#,
        label: #"CNPJ"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"br_cnpj"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"ca_sin"#,
        country: #"CA"#,
        kind: #"national_id"#,
        regex: #"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b"#,
        redaction: #"[SIN_REDACTED]"#,
        type: #"ca_sin"#,
        label: #"SIN"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [#"sin"#, #"social insurance"#, #"canada revenue"#, #"cra"#, #"employment insurance"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: #"ca_sin"#,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ca_phone"#,
        country: #"CA"#,
        kind: #"phone"#,
        regex: #"\b(\+?1[-. \t]?)?\(?\d{3}\)?[-. \t]\d{3}[-. \t]\d{4}\b"#,
        redaction: #"[CA_PHONE_REDACTED]"#,
        type: #"phone"#,
        label: #"CA_PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [#"phone"#, #"mobile"#, #"cell"#, #"tel"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ca_postal_code"#,
        country: #"CA"#,
        kind: #"postcode"#,
        regex: #"\b[A-Za-z]\d[A-Za-z][ \t-]?\d[A-Za-z]\d\b"#,
        redaction: #"[CA_POSTAL_REDACTED]"#,
        type: #"postal_code"#,
        label: #"CA_POSTAL"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [#"postal"#, #"zip"#, #"post code"#, #"mailing"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"ca_passport"#,
        country: #"CA"#,
        kind: #"passport"#,
        regex: #"\b[A-Za-z]{2}\d{6}\b"#,
        redaction: #"[CA_PASSPORT_REDACTED]"#,
        type: #"passport"#,
        label: #"CA_PASSPORT"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"passport"#, #"travel document"#, #"citizenship"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"za_id_number"#,
        country: #"ZA"#,
        kind: #"national_id"#,
        regex: #"\b(\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(\d{4})(0|1)(\d{2})\b"#,
        redaction: #"[ZA_ID_REDACTED]"#,
        type: #"za_id_number"#,
        label: #"ZA_ID"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [#"sa id"#, #"rsa id"#, #"south african id"#, #"suid-afrikaanse id"#, #"id no"#, #"id-nommer"#, #"home affairs"#],
        nearMissFallback: true,
        checksum: #"za_id"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"za_phone"#,
        country: #"ZA"#,
        kind: #"phone"#,
        regex: #"(?:\+27[ \t]?|\b0)[6-8]\d[ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: #"[PHONE_REDACTED]"#,
        type: #"za_phone"#,
        label: #"PHONE"#,
        requiresKeyword: false,
        alwaysOn: false,
        keywords: [],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"gh_ghana_card"#,
        country: #"GH"#,
        kind: #"national_id"#,
        regex: #"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b"#,
        redaction: #"[GHANA_CARD_REDACTED]"#,
        type: #"gh_ghana_card"#,
        label: #"GHANA_CARD"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"ghana card"#, #"ghanacard"#, #"ghana revenue"#, #"nia pin"#, #"personal id number"#, #"gra tin"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"it_codice_fiscale"#,
        country: #"IT"#,
        kind: #"tax_id"#,
        regex: #"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b"#,
        redaction: #"[CODICE_FISCALE_REDACTED]"#,
        type: #"it_codice_fiscale"#,
        label: #"CODICE_FISCALE"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"codice fiscale"#, #"cod. fisc"#, #"cod.fisc"#, #"c.f."#, #"anagrafe tributaria"#, #"tessera sanitaria"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"it_codice_fiscale"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"ke_kra_pin"#,
        country: #"KE"#,
        kind: #"tax_id"#,
        regex: #"\b[AP]\d{9}[A-Z]\b"#,
        redaction: #"[KRA_PIN_REDACTED]"#,
        type: #"ke_kra_pin"#,
        label: #"KRA_PIN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"kra pin"#, #"kra"#, #"tax pin"#, #"itax"#, #"pin certificate"#, #"personal identification number"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"mu_tan"#,
        country: #"MU"#,
        kind: #"tax_id"#,
        regex: #"\b[123578]\d{7}\b"#,
        redaction: #"[TAN_REDACTED]"#,
        type: #"mu_tan"#,
        label: #"TAN"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"tax account number"#, #"mauritius revenue"#, #"tan "#, #"tan:"#, #"tan no"#, #"tan number"#, #"mra tan"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"mx_rfc"#,
        country: #"MX"#,
        kind: #"tax_id"#,
        regex: #"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b"#,
        redaction: #"[RFC_REDACTED]"#,
        type: #"mx_rfc"#,
        label: #"RFC"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"rfc"#, #"homoclave"#, #"registro federal de contribuyentes"#, #"contribuyentes"#, #"constancia de situación fiscal"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"my_mykad"#,
        country: #"MY"#,
        kind: #"national_id"#,
        regex: #"\b\d{6}-?\d{2}-?\d{4}\b"#,
        redaction: #"[MYKAD_REDACTED]"#,
        type: #"my_mykad"#,
        label: #"MYKAD"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"mykad"#, #"my kad"#, #"kad pengenalan"#, #"no. kad pengenalan"#, #"nric"#, #"ic number"#, #"no. ic"#, #"mykid"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"pk_cnic"#,
        country: #"PK"#,
        kind: #"national_id"#,
        regex: #"\b\d{5}-?\d{7}-?\d\b"#,
        redaction: #"[CNIC_REDACTED]"#,
        type: #"pk_cnic"#,
        label: #"CNIC"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"cnic"#, #"nadra"#, #"nic number"#, #"identity card number"#, #"شناختی کارڈ"#, #"شناختی"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
    TorkPiiPattern(
        name: #"sg_nric"#,
        country: #"SG"#,
        kind: #"national_id"#,
        regex: #"\b[STFGM]\d{7}[A-Z]\b"#,
        redaction: #"[NRIC_REDACTED]"#,
        type: #"sg_nric"#,
        label: #"NRIC"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"nric"#, #"fin number"#, #"fin no"#, #"fin:"#, #"identity card"#, #"identification number"#, #"cpf"#, #"singpass"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"sg_nric"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"th_national_id"#,
        country: #"TH"#,
        kind: #"national_id"#,
        regex: #"\b\d-?\d{4}-?\d{5}-?\d{2}-?\d\b"#,
        redaction: #"[NATIONAL_ID_REDACTED]"#,
        type: #"th_national_id"#,
        label: #"NATIONAL_ID"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"national id"#, #"thai id"#, #"เลขประจำตัวประชาชน"#, #"บัตรประชาชน"#, #"เลขบัตร"#, #"promptpay"#],
        wholeWordKeywords: [],
        nearMissKeywords: [],
        nearMissFallback: true,
        checksum: #"th_national_id"#,
        checksumRequired: true
    ),
    TorkPiiPattern(
        name: #"id_nik"#,
        country: #"ID"#,
        kind: #"national_id"#,
        regex: #"\b\d{16}\b"#,
        redaction: #"[NIK_REDACTED]"#,
        type: #"id_nik"#,
        label: #"NIK"#,
        requiresKeyword: true,
        alwaysOn: false,
        keywords: [#"nomor induk kependudukan"#, #"kartu tanda penduduk"#, #"dukcapil"#],
        wholeWordKeywords: [#"nik"#, #"e-ktp"#, #"ektp"#, #"ktp"#, #"npwp"#],
        nearMissKeywords: [],
        nearMissFallback: false,
        checksum: nil,
        checksumRequired: false
    ),
]

// In evaluation order. Stop at the first signal a country matches.
public let torkPiiSignals: [TorkPiiSignal] = [
    TorkPiiSignal(
        country: #"AU"#,
        regex: #"\b\d{3}\s\d{3}\s\d{3}\b"#,
        flags: #""#,
        keywords: [#"tfn"#, #"tax file"#, #"medicare"#],
        wholeWordKeywords: [],
        activates: #"AU"#
    ),
    TorkPiiSignal(
        country: #"AU"#,
        regex: #"\b\d{4}\s\d{5}\s\d{1}\b"#,
        flags: #""#,
        keywords: [],
        wholeWordKeywords: [],
        activates: #"AU"#
    ),
    TorkPiiSignal(
        country: #"AU"#,
        regex: #"\b(0[2-9]|\+61)\d{8,9}\b"#,
        flags: #""#,
        keywords: [#"au"#, #"australia"#, #"australian"#],
        wholeWordKeywords: [],
        activates: #"AU"#
    ),
    TorkPiiSignal(
        country: #"GB"#,
        regex: #"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b"#,
        flags: #"i"#,
        keywords: [#"national insurance"#, #"ni number"#, #"nino"#, #"ni:"#],
        wholeWordKeywords: [],
        activates: #"GB"#
    ),
    TorkPiiSignal(
        country: #"GB"#,
        regex: #"\b[A-Z]{1,2}\d{1,2}[ \t]?\d[A-Z]{2}\b"#,
        flags: #""#,
        keywords: [#"uk"#, #"united kingdom"#, #"britain"#, #"postcode"#],
        wholeWordKeywords: [],
        activates: #"GB"#
    ),
    TorkPiiSignal(
        country: #"GB"#,
        regex: #"\b(\+44|0044)\d{10}\b"#,
        flags: #""#,
        keywords: [#"uk"#, #"united kingdom"#, #"britain"#],
        wholeWordKeywords: [],
        activates: #"GB"#
    ),
    TorkPiiSignal(
        country: #"CA"#,
        regex: #"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b"#,
        flags: #""#,
        keywords: [#"sin"#, #"social insurance"#, #"canada revenue"#, #"cra"#, #"employment insurance"#],
        wholeWordKeywords: [],
        activates: #"CA"#
    ),
    TorkPiiSignal(
        country: #"CA"#,
        regex: #"\b[A-Za-z]\d[A-Za-z][ \t]?\d[A-Za-z]\d\b"#,
        flags: #""#,
        keywords: [#"canada"#, #"canadian"#, #"postal code"#, #"province"#],
        wholeWordKeywords: [],
        activates: #"CA"#
    ),
    TorkPiiSignal(
        country: #"ZA"#,
        regex: #"\b\d{13}\b"#,
        flags: #""#,
        keywords: [#"id number"#, #"identity number"#, #"south africa"#, #"sa id"#, #"rsa"#, #"popia"#, #"fica"#],
        wholeWordKeywords: [],
        activates: #"ZA"#
    ),
    TorkPiiSignal(
        country: #"ZA"#,
        regex: #"\b(\+27|0)[6-8]\d{8}\b"#,
        flags: #""#,
        keywords: [#"south africa"#, #"za"#, #"johannesburg"#, #"cape town"#, #"durban"#, #"pretoria"#],
        wholeWordKeywords: [],
        activates: #"ZA"#
    ),
    TorkPiiSignal(
        country: #"DE"#,
        regex: #"\b[1-9]\d{10}\b"#,
        flags: #""#,
        keywords: [#"steuer"#, #"steuernummer"#, #"finanzamt"#, #"tax id"#, #"german"#],
        wholeWordKeywords: [],
        activates: #"DE"#
    ),
    TorkPiiSignal(
        country: #"DE"#,
        regex: #"\b(\+49|0049)\d{10,11}\b"#,
        flags: #""#,
        keywords: [#"germany"#, #"german"#, #"deutschland"#, #"de"#],
        wholeWordKeywords: [],
        activates: #"DE"#
    ),
    TorkPiiSignal(
        country: #"NG"#,
        regex: #"\b\d{11}\b"#,
        flags: #""#,
        keywords: [#"bvn"#, #"nin"#, #"bank verification"#, #"nigeria"#, #"nigerian"#],
        wholeWordKeywords: [],
        activates: #"NG"#
    ),
    TorkPiiSignal(
        country: #"NG"#,
        regex: #"\b(\+234|0)[7-9]\d{9}\b"#,
        flags: #""#,
        keywords: [#"nigeria"#, #"nigerian"#, #"lagos"#, #"abuja"#],
        wholeWordKeywords: [],
        activates: #"NG"#
    ),
    TorkPiiSignal(
        country: #"AE"#,
        regex: #"\b784[- \t]\d{4}[- \t]\d{7}[- \t]\d{1}\b"#,
        flags: #""#,
        keywords: [],
        wholeWordKeywords: [],
        activates: #"AE"#
    ),
    TorkPiiSignal(
        country: #"AE"#,
        regex: #"\b(\+971|00971)\d{9}\b"#,
        flags: #""#,
        keywords: [#"uae"#, #"emirates"#, #"dubai"#, #"abu dhabi"#],
        wholeWordKeywords: [],
        activates: #"AE"#
    ),
    TorkPiiSignal(
        country: #"IN"#,
        regex: #"\b[A-Z]{5}\d{4}[A-Z]{1}\b"#,
        flags: #""#,
        keywords: [],
        wholeWordKeywords: [],
        activates: #"IN"#
    ),
    TorkPiiSignal(
        country: #"IN"#,
        regex: #"\b\d{4}\s\d{4}\s\d{4}\b"#,
        flags: #""#,
        keywords: [#"aadhaar"#, #"aadhar"#, #"india"#, #"indian"#],
        wholeWordKeywords: [],
        activates: #"IN"#
    ),
    TorkPiiSignal(
        country: #"SA"#,
        regex: #"\b1\d{9}\b"#,
        flags: #""#,
        keywords: [#"saudi"#, #"ksa"#, #"riyadh"#, #"national id"#, #"iqama"#],
        wholeWordKeywords: [],
        activates: #"SA"#
    ),
    TorkPiiSignal(
        country: #"SA"#,
        regex: #"\b(\+966|00966)\d{9}\b"#,
        flags: #""#,
        keywords: [#"saudi"#, #"ksa"#, #"riyadh"#],
        wholeWordKeywords: [],
        activates: #"SA"#
    ),
    TorkPiiSignal(
        country: #"BR"#,
        regex: #"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b"#,
        flags: #""#,
        keywords: [#"cpf"#, #"brazil"#, #"brasil"#, #"brazilian"#],
        wholeWordKeywords: [],
        activates: #"BR"#
    ),
    TorkPiiSignal(
        country: #"BR"#,
        regex: #"\b(\+55|0055)\d{11}\b"#,
        flags: #""#,
        keywords: [#"brazil"#, #"brasil"#],
        wholeWordKeywords: [],
        activates: #"BR"#
    ),
    TorkPiiSignal(
        country: #"JP"#,
        regex: #"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        flags: #""#,
        keywords: [#"my number"#, #"individual number"#, #"マイナンバー"#, #"個人番号"#, #"japan"#, #"japanese"#, #"日本"#, #"tokyo"#, #"osaka"#, #"nagoya"#, #"yokohama"#],
        wholeWordKeywords: [],
        activates: #"JP"#
    ),
    TorkPiiSignal(
        country: #"JP"#,
        regex: #"\b(\+81|0081)[ \t]?\d{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        flags: #""#,
        keywords: [#"japan"#, #"japanese"#, #"日本"#, #"tokyo"#, #"osaka"#],
        wholeWordKeywords: [],
        activates: #"JP"#
    ),
    TorkPiiSignal(
        country: #"CN"#,
        regex: #"\b\d{17}[0-9Xx]\b"#,
        flags: #""#,
        keywords: [#"resident id"#, #"resident identity"#, #"identity card"#, #"id card"#, #"身份证"#, #"身份證"#, #"居民身份证"#, #"china"#, #"chinese"#, #"prc"#, #"beijing"#, #"shanghai"#, #"shenzhen"#, #"guangzhou"#],
        wholeWordKeywords: [],
        activates: #"CN"#
    ),
    TorkPiiSignal(
        country: #"CN"#,
        regex: #"\b(\+86|0086)[ \t]?1[3-9]\d{9}\b"#,
        flags: #""#,
        keywords: [#"china"#, #"chinese"#, #"prc"#, #"beijing"#, #"shanghai"#, #"shenzhen"#, #"guangzhou"#],
        wholeWordKeywords: [],
        activates: #"CN"#
    ),
    TorkPiiSignal(
        country: #"KR"#,
        regex: #"\b\d{6}-?[1-8]\d{6}\b"#,
        flags: #""#,
        keywords: [#"resident registration"#, #"resident number"#, #"rrn"#, #"jumin"#, #"주민등록번호"#, #"주민번호"#, #"korea"#, #"korean"#, #"seoul"#, #"busan"#, #"incheon"#],
        wholeWordKeywords: [],
        activates: #"KR"#
    ),
    TorkPiiSignal(
        country: #"KR"#,
        regex: #"\b(\+82|0082)[ \t]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        flags: #""#,
        keywords: [#"korea"#, #"korean"#, #"seoul"#, #"busan"#, #"incheon"#],
        wholeWordKeywords: [],
        activates: #"KR"#
    ),
    TorkPiiSignal(
        country: #"GH"#,
        regex: #"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b"#,
        flags: #""#,
        keywords: [#"ghana card"#, #"ghanacard"#, #"ghana"#, #"accra"#, #"kumasi"#, #"nia pin"#, #"gra tin"#],
        wholeWordKeywords: [],
        activates: #"GH"#
    ),
    TorkPiiSignal(
        country: #"GH"#,
        regex: #"\b(\+233|00233)[ \t]?\d{9}\b"#,
        flags: #""#,
        keywords: [#"ghana"#, #"ghanaian"#, #"accra"#, #"kumasi"#, #"tema"#],
        wholeWordKeywords: [],
        activates: #"GH"#
    ),
    TorkPiiSignal(
        country: #"IT"#,
        regex: #"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b"#,
        flags: #""#,
        keywords: [#"codice fiscale"#, #"cod. fisc"#, #"c.f."#, #"anagrafe tributaria"#, #"italy"#, #"italia"#, #"italian"#, #"italiana"#, #"roma"#, #"milano"#, #"napoli"#, #"torino"#],
        wholeWordKeywords: [],
        activates: #"IT"#
    ),
    TorkPiiSignal(
        country: #"IT"#,
        regex: #"\b(\+39|0039)[ \t]?\d{9,11}\b"#,
        flags: #""#,
        keywords: [#"italy"#, #"italia"#, #"italian"#, #"italiana"#, #"roma"#, #"milano"#, #"napoli"#, #"torino"#],
        wholeWordKeywords: [],
        activates: #"IT"#
    ),
    TorkPiiSignal(
        country: #"KE"#,
        regex: #"\b[AP]\d{9}[A-Z]\b"#,
        flags: #""#,
        keywords: [#"kra"#, #"itax"#, #"tax pin"#, #"kenya"#, #"kenyan"#, #"nairobi"#, #"mombasa"#, #"kisumu"#],
        wholeWordKeywords: [],
        activates: #"KE"#
    ),
    TorkPiiSignal(
        country: #"KE"#,
        regex: #"\b(\+254|00254)[ \t]?\d{9}\b"#,
        flags: #""#,
        keywords: [#"kenya"#, #"kenyan"#, #"nairobi"#, #"mombasa"#, #"kisumu"#],
        wholeWordKeywords: [],
        activates: #"KE"#
    ),
    TorkPiiSignal(
        country: #"MU"#,
        regex: #"\b[123578]\d{7}\b"#,
        flags: #""#,
        keywords: [#"mauritius"#, #"mauritian"#, #"port louis"#, #"mauritius revenue"#, #"mra tan"#],
        wholeWordKeywords: [],
        activates: #"MU"#
    ),
    TorkPiiSignal(
        country: #"MU"#,
        regex: #"\b(\+230|00230)[ \t]?\d{7,8}\b"#,
        flags: #""#,
        keywords: [#"mauritius"#, #"mauritian"#, #"port louis"#],
        wholeWordKeywords: [],
        activates: #"MU"#
    ),
    TorkPiiSignal(
        country: #"MX"#,
        regex: #"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b"#,
        flags: #""#,
        keywords: [#"rfc"#, #"homoclave"#, #"contribuyentes"#, #"mexico"#, #"méxico"#, #"mexican"#, #"mexicano"#, #"cdmx"#, #"guadalajara"#, #"monterrey"#],
        wholeWordKeywords: [],
        activates: #"MX"#
    ),
    TorkPiiSignal(
        country: #"MX"#,
        regex: #"\b(\+52|0052)[ \t]?\d{10}\b"#,
        flags: #""#,
        keywords: [#"mexico"#, #"méxico"#, #"mexican"#, #"mexicano"#, #"cdmx"#, #"guadalajara"#, #"monterrey"#],
        wholeWordKeywords: [],
        activates: #"MX"#
    ),
    TorkPiiSignal(
        country: #"MY"#,
        regex: #"\b\d{6}-\d{2}-\d{4}\b"#,
        flags: #""#,
        keywords: [#"mykad"#, #"kad pengenalan"#, #"nric"#, #"malaysia"#, #"malaysian"#, #"kuala lumpur"#, #"johor"#, #"penang"#, #"putrajaya"#, #"selangor"#],
        wholeWordKeywords: [],
        activates: #"MY"#
    ),
    TorkPiiSignal(
        country: #"MY"#,
        regex: #"\b\d{12}\b"#,
        flags: #""#,
        keywords: [#"mykad"#, #"my kad"#, #"kad pengenalan"#, #"mykid"#],
        wholeWordKeywords: [],
        activates: #"MY"#
    ),
    TorkPiiSignal(
        country: #"MY"#,
        regex: #"\b(\+60|0060)[ \t]?\d{9,10}\b"#,
        flags: #""#,
        keywords: [#"malaysia"#, #"malaysian"#, #"kuala lumpur"#, #"johor"#, #"penang"#],
        wholeWordKeywords: [],
        activates: #"MY"#
    ),
    TorkPiiSignal(
        country: #"PK"#,
        regex: #"\b\d{5}-\d{7}-\d\b"#,
        flags: #""#,
        keywords: [#"cnic"#, #"nadra"#, #"pakistan"#, #"pakistani"#, #"karachi"#, #"lahore"#, #"islamabad"#, #"rawalpindi"#, #"شناختی"#],
        wholeWordKeywords: [],
        activates: #"PK"#
    ),
    TorkPiiSignal(
        country: #"PK"#,
        regex: #"\b\d{13}\b"#,
        flags: #""#,
        keywords: [#"cnic"#, #"nadra"#, #"شناختی"#],
        wholeWordKeywords: [],
        activates: #"PK"#
    ),
    TorkPiiSignal(
        country: #"PK"#,
        regex: #"\b(\+92|0092)[ \t]?3\d{9}\b"#,
        flags: #""#,
        keywords: [#"pakistan"#, #"pakistani"#, #"karachi"#, #"lahore"#, #"islamabad"#],
        wholeWordKeywords: [],
        activates: #"PK"#
    ),
    TorkPiiSignal(
        country: #"SG"#,
        regex: #"\b[STFGM]\d{7}[A-Z]\b"#,
        flags: #""#,
        keywords: [#"nric"#, #"singpass"#, #"cpf"#, #"iras"#, #"singapore"#, #"singaporean"#],
        wholeWordKeywords: [],
        activates: #"SG"#
    ),
    TorkPiiSignal(
        country: #"SG"#,
        regex: #"\b(\+65|0065)[ \t]?[689]\d{3}[ \t]?\d{4}\b"#,
        flags: #""#,
        keywords: [#"singapore"#, #"singaporean"#],
        wholeWordKeywords: [],
        activates: #"SG"#
    ),
    TorkPiiSignal(
        country: #"TH"#,
        regex: #"\b\d-\d{4}-\d{5}-\d{2}-\d\b"#,
        flags: #""#,
        keywords: [#"national id"#, #"thai"#, #"thailand"#, #"เลขประจำตัวประชาชน"#, #"บัตรประชาชน"#, #"bangkok"#, #"promptpay"#],
        wholeWordKeywords: [],
        activates: #"TH"#
    ),
    TorkPiiSignal(
        country: #"TH"#,
        regex: #"\b\d{13}\b"#,
        flags: #""#,
        keywords: [#"thai id"#, #"thailand"#, #"เลขประจำตัวประชาชน"#, #"บัตรประชาชน"#, #"promptpay"#],
        wholeWordKeywords: [],
        activates: #"TH"#
    ),
    TorkPiiSignal(
        country: #"TH"#,
        regex: #"\b(\+66|0066)[ \t]?\d{9}\b"#,
        flags: #""#,
        keywords: [#"thailand"#, #"thai"#, #"bangkok"#, #"phuket"#, #"chiang mai"#],
        wholeWordKeywords: [],
        activates: #"TH"#
    ),
    TorkPiiSignal(
        country: #"ID"#,
        regex: #"\b\d{16}\b"#,
        flags: #""#,
        keywords: [#"nomor induk kependudukan"#, #"kartu tanda penduduk"#, #"dukcapil"#],
        wholeWordKeywords: [#"nik"#, #"e-ktp"#, #"ektp"#, #"ktp"#, #"npwp"#],
        activates: #"ID"#
    ),
    TorkPiiSignal(
        country: #"ID"#,
        regex: #"\b(\+62|0062)[ \t]?\d{9,12}\b"#,
        flags: #""#,
        keywords: [#"indonesia"#, #"indonesian"#, #"jakarta"#, #"surabaya"#, #"bandung"#, #"medan"#, #"bali"#],
        wholeWordKeywords: [],
        activates: #"ID"#
    ),
]
